# Generated by Django 5.1.1 on 2024-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=150)),
                ('answer', models.TextField(max_length=50)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
